# Basic configuration
# theme: jekyll-theme-hydeout # Github will complain about this one
remote-theme: fongandrew/hydeout

title: Circus
tagline: '/dev/null'
description: 'Each virtue and each wisdom needs parading in one’s own time, and must not last forever.'
#url: https://rscircus.github.io
#baseurl: '/'

github:
  repo: 'https://github.com/rscircus'

markdown: kramdown

# Site config
# paginate: 5

# TODO: Adapt local Jekyll config:
# # Dependencies
# markdown: redcarpet
# highlighter: pygments
#
# # Permalinks
# permalink: pretty
# relative_permalinks: true
#

