# Basic configuration
remote-theme: fongandrew/hydeout
title: R's Circus.
description: Each virtue and each wisdom needs parading in one’s own time, and must not last forever.
author:
    name: 'Roland Siegbert'
    url: https://twitter.com/rscircus

# Site config
paginate: 5

# TODO: Adapt local Jekyll config:
# # Dependencies
# markdown: redcarpet
# highlighter: pygments
#
# # Permalinks
# permalink: pretty
# relative_permalinks: true
#

