# Basic configuration
# theme: jekyll-theme-hydeout # Github will complain about this one
remote-theme: yous/hydeout

title: Circus
tagline: 'wordsmithing'
description: 'Each virtue and each wisdom needs parading in one’s own time, and must not last forever.'
#url: https://rscircus.github.io
#baseurl: '/'

github:
  repo: 'https://github.com/rscircus'

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator: <!-- more -->
      layout: post

paginate: 5

# TODO: Adapt local Jekyll config:
# # Dependencies
# markdown: redcarpet
# highlighter: pygments
#
# # Permalinks
# permalink: pretty
# relative_permalinks: true
#

