theme = 'PaperModded'
baseURL = "https://rscircus.github.io"
languageCode = "en-us"
title = "R's 🎩"
pygmentsUseClasses = true
enableInlineShortcodes = true
enableRobotsTXT = true

[params]
mode="toggle"
defaultTheme="auto"
ShowWordCount=true
ShowToc=true
ShowCodeCopyButtons=true
useCDN=false
subtitle = "Fascinated by Computer Science, Life Sciences, DIY hardware, and Accessibility for the Deaf and Mathematics"

# Typography
google_fonts = [
  ["Fira Code", "400, 700"],
  ["Open Sans", "400, 400i, 700, 700i"]
]
heading_font = "Fira Code"
body_font = "Open Sans"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://gitlab.com/rscircus/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url ="/projects"
weight = 2

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.97.1"

[author]
name = "Roland Siegbert"
homepage = "https://rscircus.github.io"

[markup.goldmark.renderer]
unsafe = true
